/* global React, Icon */
const { useState: useStateBO } = React;

// ──────────────────────────────────────────────────────────────────────────
// Builder-mode affordances.
//
// Sits on top of the canvas's transformed world. Renders:
//   • An output handle on every hovered / selected node — drag to connect,
//     or click "+" to add a stage downstream
//   • A "+" pin on every hovered / selected edge — click to insert an
//     operator into the connection
//   • A "×" delete pin alongside the edge "+"
//   • A floating action toolbar above a selected node (duplicate / delete)
//   • The operator picker popover that appears when any "+" is clicked
//
// Functionality is presentational only — clicks open the picker but do not
// mutate the workflow. This is a click-through prototype.
// ──────────────────────────────────────────────────────────────────────────

const NODE_W = 192;
const NODE_H = 80;
const ROUTING_W = 124;
const ROUTING_H = 50;

const STAGE_TYPES = [
  { kind: "worker", label: "worker",  icon: "zap",       desc: "skills · prompt · result" },
  { kind: "switch", label: "switch",  icon: "gitBranch", desc: "n-way enum routing" },
  { kind: "branch", label: "branch",  icon: "gitBranch", desc: "if / else" },
  { kind: "map",    label: "for-each",icon: "refresh",   desc: "iterate a list, fan-out" },
  { kind: "loop",   label: "loop",    icon: "refresh",   desc: "re-enter while condition" },
  { kind: "join",   label: "join",    icon: "workflow",  desc: "wait for N upstreams" },
];

// ── helpers ───────────────────────────────────────────────────────────────

function nodeRect(stage, pos) {
  // The routing node centers itself inside a worker-sized footprint.
  return { x: pos.x, y: pos.y, w: NODE_W, h: NODE_H };
}

function edgeMidpoint(d) {
  // Crude midpoint by sampling. We accept the cubic d string already
  // generated by pathBetween; SVG getPointAtLength would be exact but we
  // only need a usable insertion anchor. Parse first M and last point.
  const m = d.match(/M\s+([-\d.]+)\s+([-\d.]+)/);
  const last = d.match(/[\d.-]+\s+[\d.-]+\s*$/);
  if (!m || !last) return null;
  const [ax, ay] = [parseFloat(m[1]), parseFloat(m[2])];
  const [bx, by] = last[0].trim().split(/\s+/).map(parseFloat);
  return { x: (ax + bx) / 2, y: (ay + by) / 2 };
}

// ── handles ───────────────────────────────────────────────────────────────

function OutputHandle({ stage, pos, isHovered, isSelected, flow, zoom, onAdd }) {
  const horizontal = flow !== "vertical";
  const isRouting = stage.kind !== "worker";
  const w = isRouting ? ROUTING_W : NODE_W;
  const h = isRouting ? ROUTING_H : NODE_H;
  const cx = pos.x + (NODE_W / 2);
  const cy = pos.y + (NODE_H / 2);
  const x = horizontal ? pos.x + (isRouting ? (NODE_W + w) / 2 : w) : cx;
  const y = horizontal ? cy : pos.y + (isRouting ? (NODE_H + h) / 2 : h);

  if (!isHovered && !isSelected) return null;
  const inv = 1 / zoom;

  return (
    <div style={{
      position: "absolute",
      left: x, top: y,
      width: 0, height: 0,
      pointerEvents: "auto",
    }}>
      {/* All visuals live inside a counter-scaled inner container so they
          render at a constant pixel size regardless of canvas zoom. */}
      <div style={{
        position: "absolute",
        left: 0, top: 0,
        transform: `scale(${inv}) translate(-50%, -50%)`,
        transformOrigin: "0 0",
        display: "flex", alignItems: "center", gap: 8,
        whiteSpace: "nowrap",
      }}>
        <div
          title="drag to connect"
          style={{
            width: 12, height: 12,
            borderRadius: 999,
            background: "var(--co-accent)",
            border: "2px solid var(--co-bg-1)",
            boxShadow: "0 0 0 1px var(--co-accent), 0 0 8px color-mix(in oklab, var(--co-accent) 50%, transparent)",
            cursor: "crosshair",
            flex: "0 0 12px",
          }}
        />
        <button
          type="button"
          onClick={(e) => { e.stopPropagation(); onAdd({ x, y }); }}
          title="add next stage"
          style={{
            width: 22, height: 22,
            padding: 0,
            borderRadius: 999,
            background: "var(--co-bg-2)",
            border: "1px dashed var(--co-accent)",
            color: "var(--co-accent)",
            display: "flex", alignItems: "center", justifyContent: "center",
            fontFamily: "var(--co-font-mono)", fontSize: 14, fontWeight: 600,
            cursor: "pointer",
            lineHeight: 1,
          }}
        >+</button>
      </div>
    </div>
  );
}

function NodeToolbar({ stage, pos, zoom, onDuplicate, onDelete }) {
  const cx = pos.x + (NODE_W / 2);
  const inv = 1 / zoom;
  return (
    <div style={{
      position: "absolute",
      left: cx, top: pos.y,
      width: 0, height: 0,
      pointerEvents: "auto",
    }}>
      <div style={{
        position: "absolute", left: 0, top: 0,
        transform: `scale(${inv}) translate(-50%, calc(-100% - 14px))`,
        transformOrigin: "0 0",
        display: "inline-flex", alignItems: "center",
        gap: 2,
        padding: 3,
        background: "var(--co-bg-1)",
        border: "1px solid var(--co-border-2)",
        borderRadius: 6,
        boxShadow: "var(--co-shadow-2)",
        whiteSpace: "nowrap",
      }}>
        <ToolbarBtn icon="copy" label="duplicate" onClick={onDuplicate} />
        <span style={{ width: 1, height: 16, background: "var(--co-border-1)" }} />
        <ToolbarBtn icon="x" label="delete" danger onClick={onDelete} />
      </div>
    </div>
  );
}

function ToolbarBtn({ icon, label, danger, onClick }) {
  const [hover, setHover] = useStateBO(false);
  return (
    <button
      type="button"
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      onClick={(e) => { e.stopPropagation(); onClick?.(); }}
      title={label}
      style={{
        display: "inline-flex", alignItems: "center", gap: 4,
        padding: "3px 7px",
        background: hover ? (danger ? "var(--co-danger-soft)" : "var(--co-bg-3)") : "transparent",
        border: "none", borderRadius: 4,
        color: hover && danger ? "var(--co-danger)" : "var(--co-text)",
        cursor: "pointer",
        fontFamily: "var(--co-font-sans)", fontSize: 11,
      }}
    >
      <Icon name={icon} size={11} color="currentColor" />
      {label}
    </button>
  );
}

function EdgeAffordance({ edgeKey, mid, isHovered, isSelected, zoom, onInsert, onDelete }) {
  if (!mid) return null;
  if (!isHovered && !isSelected) return null;
  const inv = 1 / zoom;
  return (
    <div style={{
      position: "absolute",
      left: mid.x, top: mid.y,
      width: 0, height: 0,
      pointerEvents: "auto",
    }}>
      <div style={{
        position: "absolute", left: 0, top: 0,
        transform: `scale(${inv}) translate(-50%, -50%)`,
        transformOrigin: "0 0",
        display: "inline-flex", alignItems: "center",
        gap: 4,
      }}>
        <button
          type="button"
          onClick={(e) => { e.stopPropagation(); onInsert({ x: mid.x, y: mid.y }); }}
          title="insert operator on this connection"
          style={{
            width: 24, height: 24, padding: 0,
            borderRadius: 999,
            background: "var(--co-accent)",
            border: "2px solid var(--co-bg-1)",
            boxShadow: "0 0 0 1px var(--co-accent), 0 2px 8px rgba(0,0,0,0.4)",
            color: "var(--co-accent-ink)",
            display: "flex", alignItems: "center", justifyContent: "center",
            fontFamily: "var(--co-font-mono)", fontSize: 14, fontWeight: 700,
            cursor: "pointer",
            lineHeight: 1,
          }}
        >+</button>
        <button
          type="button"
          onClick={(e) => { e.stopPropagation(); onDelete(edgeKey); }}
          title="delete this connection"
          style={{
            width: 20, height: 20, padding: 0,
            borderRadius: 999,
            background: "var(--co-bg-1)",
            border: "1px solid var(--co-danger)",
            color: "var(--co-danger)",
            display: "flex", alignItems: "center", justifyContent: "center",
            cursor: "pointer",
          }}
        >
          <Icon name="x" size={10} color="currentColor" />
        </button>
      </div>
    </div>
  );
}

// ── operator picker ───────────────────────────────────────────────────────

function OperatorPicker({ anchor, context, onClose }) {
  // anchor is already in SCREEN coords. The picker renders fixed-position
  // outside the canvas world transform, so it never inherits zoom.
  return (
    <>
      <div onClick={onClose} style={{
        position: "fixed", inset: 0, zIndex: 60, background: "transparent",
      }} />
      <div style={{
        position: "fixed",
        left: anchor.x, top: anchor.y + 14,
        transform: "translate(-50%, 0)",
        zIndex: 65,
        width: 240,
        background: "var(--co-bg-2)",
        border: "1px solid var(--co-border-2)",
        borderRadius: 8,
        boxShadow: "var(--co-shadow-3)",
        overflow: "hidden",
        pointerEvents: "auto",
      }}>
        <div style={{
          padding: "8px 10px 6px",
          borderBottom: "1px solid var(--co-border-1)",
          display: "flex", alignItems: "center", justifyContent: "space-between",
        }}>
          <span style={{
            fontFamily: "var(--co-font-mono)", fontSize: 10,
            letterSpacing: "0.08em", textTransform: "uppercase",
            color: "var(--co-text-subtle)", fontWeight: 500,
          }}>
            {context === "insert" ? "insert on edge" : "add next stage"}
          </span>
          <button
            type="button"
            onClick={onClose}
            style={{
              background: "transparent", border: "none", padding: 2, cursor: "pointer",
              color: "var(--co-text-subtle)",
              display: "inline-flex", alignItems: "center",
            }}
          ><Icon name="x" size={10} color="currentColor" /></button>
        </div>
        <div style={{ padding: 4 }}>
          {STAGE_TYPES.map(t => (
            <button
              key={t.kind}
              type="button"
              onClick={onClose}
              style={{
                width: "100%",
                display: "grid",
                gridTemplateColumns: "22px 1fr",
                alignItems: "center",
                gap: 8,
                padding: "6px 8px",
                background: "transparent",
                border: "none",
                borderRadius: 5,
                cursor: "pointer",
                textAlign: "left",
                fontFamily: "var(--co-font-mono)", fontSize: 11.5,
                color: "var(--co-text)",
              }}
              onMouseEnter={(e) => { e.currentTarget.style.background = "var(--co-bg-3)"; }}
              onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; }}
            >
              <span style={{
                width: 22, height: 22, borderRadius: 5,
                background: t.kind === "worker" ? "color-mix(in oklab, var(--co-accent) 14%, var(--co-bg-3))" : "var(--co-bg-3)",
                border: "1px solid var(--co-border-2)",
                display: "flex", alignItems: "center", justifyContent: "center",
                color: t.kind === "worker" ? "var(--co-accent)" : "var(--co-fg-2)",
              }}>
                <Icon name={t.icon} size={11} color="currentColor" />
              </span>
              <span style={{ display: "flex", flexDirection: "column", lineHeight: 1.2 }}>
                <span style={{ color: "var(--co-text-strong)", fontWeight: 500 }}>{t.label}</span>
                <span style={{ color: "var(--co-text-subtle)", fontSize: 10 }}>{t.desc}</span>
              </span>
            </button>
          ))}
        </div>
      </div>
    </>
  );
}

// ── tips panel ────────────────────────────────────────────────────────────

function BuilderTips() {
  const [open, setOpen] = useStateBO(true);
  if (!open) {
    return (
      <button
        type="button"
        onClick={() => setOpen(true)}
        title="builder tips"
        style={{
          position: "absolute", left: 16, top: 16, zIndex: 8,
          width: 28, height: 28,
          padding: 0,
          background: "var(--co-bg-2)",
          border: "1px solid var(--co-border-1)",
          borderRadius: 8,
          color: "var(--co-text-muted)",
          display: "flex", alignItems: "center", justifyContent: "center",
          cursor: "pointer",
        }}
      >
        <span style={{ fontFamily: "var(--co-font-mono)", fontSize: 13, fontWeight: 700 }}>?</span>
      </button>
    );
  }
  return (
    <div style={{
      position: "absolute", left: 16, top: 16, zIndex: 8,
      width: 240,
      background: "var(--co-bg-2)",
      border: "1px solid var(--co-border-1)",
      borderRadius: 8,
      boxShadow: "var(--co-shadow-2)",
      overflow: "hidden",
      fontFamily: "var(--co-font-sans)",
    }}>
      <div style={{
        padding: "7px 10px 6px",
        background: "var(--co-bg-3)",
        borderBottom: "1px solid var(--co-border-1)",
        display: "flex", alignItems: "center", justifyContent: "space-between",
      }}>
        <span style={{
          fontFamily: "var(--co-font-mono)", fontSize: 10,
          letterSpacing: "0.08em", textTransform: "uppercase",
          color: "var(--co-text-subtle)", fontWeight: 500,
        }}>builder · how-to</span>
        <button type="button" onClick={() => setOpen(false)} style={{
          background: "transparent", border: "none", padding: 2, cursor: "pointer",
          color: "var(--co-text-subtle)", display: "inline-flex", alignItems: "center",
        }}><Icon name="x" size={10} color="currentColor" /></button>
      </div>
      <div style={{ padding: "8px 10px", display: "flex", flexDirection: "column", gap: 6 }}>
        <TipRow icon="+" label="hover a node" desc="drag the handle or click + to add a stage downstream" />
        <TipRow icon="+" label="hover a connection" desc="click + to insert an operator on the edge" />
        <TipRow icon="×" label="click a node or edge" desc="floating toolbar to duplicate or delete" />
      </div>
    </div>
  );
}

function TipRow({ icon, label, desc }) {
  return (
    <div style={{ display: "grid", gridTemplateColumns: "18px 1fr", gap: 8, alignItems: "flex-start" }}>
      <span style={{
        width: 18, height: 18,
        borderRadius: 4,
        background: icon === "×" ? "var(--co-danger-soft)" : "var(--co-accent-soft)",
        color: icon === "×" ? "var(--co-danger)" : "var(--co-accent)",
        display: "flex", alignItems: "center", justifyContent: "center",
        fontFamily: "var(--co-font-mono)", fontSize: 12, fontWeight: 700,
        lineHeight: 1,
      }}>{icon}</span>
      <div style={{ lineHeight: 1.35, paddingTop: 1 }}>
        <div style={{ fontFamily: "var(--co-font-mono)", fontSize: 11, color: "var(--co-text)" }}>{label}</div>
        <div style={{ fontSize: 11, color: "var(--co-text-subtle)" }}>{desc}</div>
      </div>
    </div>
  );
}

// ──────────────────────────────────────────────────────────────────────────

function BuilderOverlay({
  workflow, positions, flow, edgePaths, zoom,
  hoveredNodeId, hoveredEdgeKey,
  selectedNodeId, selectedEdgeKey,
  setPicker,
  onDeleteEdge,
}) {
  return (
    <>
      {/* Per-node affordances */}
      {workflow.stages.map(s => {
        const p = positions[s.id];
        if (!p) return null;
        const hovered = hoveredNodeId === s.id;
        const selected = selectedNodeId === s.id;
        return (
          <React.Fragment key={s.id}>
            <OutputHandle
              stage={s} pos={p} zoom={zoom}
              isHovered={hovered} isSelected={selected}
              flow={flow}
              onAdd={(anchor) => setPicker({ kind: "after-node", anchor, stageId: s.id })}
            />
            {selected && (
              <NodeToolbar
                stage={s} pos={p} zoom={zoom}
                onDuplicate={() => {}}
                onDelete={() => {}}
              />
            )}
          </React.Fragment>
        );
      })}

      {/* Per-edge affordances */}
      {workflow.edges.map((edge, i) => {
        const key = `${edge.from}→${edge.to}`;
        const mid = edgeMidpoint(edgePaths[key] || "");
        return (
          <EdgeAffordance
            key={i}
            edgeKey={key}
            mid={mid}
            isHovered={hoveredEdgeKey === key}
            isSelected={selectedEdgeKey === key}
            zoom={zoom}
            onInsert={(anchor) => setPicker({ kind: "insert-edge", anchor, edgeKey: key })}
            onDelete={onDeleteEdge}
          />
        );
      })}
    </>
  );
}

Object.assign(window, { BuilderOverlay, BuilderTips, OperatorPicker });
